version: 3

services:
  feeds:
    imagem: pokemons
    build: ./dockerfiles/services
    hostname: pokemons
    expose:
      - "5000"
    volumes:
      - "./pokemons:/service"
    command: python3 service.py
    networks:
      pokemonsnet:
        ipv4_address: 172.29.1.1

  database:
    image: mysql
    hostname: database
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      pokemons:
        ipv4_address: 172.29.1.4

  files:
    image: files
    build: ./dockerfiles/nginx/
    volumes:
      - "./assets/images:/usr/share/nginx/html"
    networks:
      pokemons:
        ipv4_address: 172.29.1.5

networks:
  pokemonsnet:
    ipam:
      driver: default
      config:
        - subnet: 172.29.1.0/16
